---
title: "text_ikk_intro"
author: "noah"
date: "24 3 2020"
output: html_document
---

Der Einfluss einer hierarchischen Struktur auf eine abhängige Variable kann durch die Intraklassen Korrelation (IKK) beschrieben werden. Die Intraklassen Korrelation beschreibt den Grad der Ähnlichkeit von Level-1 Einheiten innerhalb einer Level-2 Einheit und kann als Verhältnis der Varianz zwischen den Level-2 Einheiten und der Gesamtvarianz beschrieben werden \citep{FieldAndy2013DsuR, SnijdersTomA.B2012Ma:a, twisk_2006}. Diese Varianzen ergeben sich gemäss Snijders und Bosker \citeyearpar{SnijdersTomA.B2012Ma:a} aus dem \textit{random effects ANOVA} Modell, das bei der Modellierung von Multilevel Modellen oft auch als leeres Modell bezeichnet wird:
$$
Y_{ij} = \mu + U_{j} + R_{ij}
$$
Die abhängige Variable $Y_{ij}$ beschreibt in unserem Beispiel die erreichte Punktzahl des Schulkindes $i$ aus der Klasse $j$. Der Gesamtmittelwert aller Schulkinder wird mit $\mu$ bezeichnet, wobei $U_{j}$ die zufällige Abweichung einer Klasse $j$ und $R_{ij}$ die zufällige Abweichung eines Schulkindes $i$ der Klasse $j$ von diesem Gesamtmittelwert beschreiben. Dabei ist zu beachten, dass der Erwartungswert beider Zufallsvariablen $U_{j}$ und $R_{ij}$ als 0 angenommen wird. Die Varianz von $U_{j}$ wird als \textit{between-group variance} $\tau_{0}^2$ und von $R_{ij}$ als \textit{within-group variance} $\sigma^2$ bezeichnet.

Bei der IKK wird von einer Korrelation gesprochen, da es sich um die Korrelation zwischen zweier zufällig gewählter Level-1 Einheiten aus der selben Level-2 Einheit handelt. Bezogen auf unser Beispiel gibt die IKK an, wie stark sich Schulkinder aus der selben Klasse bezüglich ihrer erreichten Punktzahl ähneln. Ist die Korrelation zwischen den Schulkindern hoch, kann man davon ausgehen, dass die Klasse als Level-2 Einheit einen bedeutenden Anteil an der Gesamtvarianz erklärt. Ist die Korrelation niedrig hat die Klassenzugehörigkeit eher einen kleineren Einfluss auf die Prüfungsleistung. Dieser Zusammenhang wird etwas klarer, wenn man ihn anhand der Formel zur Berechnung der Intraklassen Korrelation Koeffizienten $\rho_{I}$ erklärt:
$$
\rho_{I} = \dfrac{\tau_{0}^{2}}{\tau_{0}^{2} + \sigma^{2}}
$$} 
Dabei beschreibt $\tau_{0}^2$ die \textit{between-group variance}. In unserem Beispiel wäre das die Varianz der erreichten Punktzahl zwischen den verschiedenen Klassen. Die Gesamtvarianz setzt sich aus der \textit{between-group variance} und der \textit{within-group variance} zusammen. Die Varianz innerhalb der Klassen wird, wie bereits erwähnt, mit $\sigma^2$ bezeichnet. Besteht nun innerhalb der Klassen eine kleine Varianz zwischen den Ergebnissen der Schulkinder ergibt sich eine grössere Intraklassen Korrelation. Steigt die Varianz innerhalb der Klassen an, wird der Nenner der Formel grösser und mit einem wachsenden Nenner, verringert sich die Intraklassen Korrelation.