---
title: "text_study_2"
author: "noah"
date: "23 3 2020"
output: html_document
---
In der zweiten Studie wurde untersucht, wie zuverlässig LM und HLM einen Effekt einer Intervention finden, wenn dieser Effekt auch effektiv vorhanden ist. Die Fähigkeit einen Effekt zu finden, wenn er auch wirklich vorhanden ist wird Power genannt. Die Power steht in einem direkten Zusammenhang mit der Stichprobengrösse, so dass eine steigende Stichprobengrösse zu einer höheren Power führt (Snijders & Bosker, 2012). Folglich würde eine so grosse Stichprobe aus Studie 1 wahrscheinlich zu keinen Unterschieden in der Power zwischen den beiden Methoden führen. Allerdings ist es in der Praxis oft nicht möglich, eine solche grosse Stichprobe von insgesamt 15000 Beobachtungen zu erheben. Daher wird in dieser zweiten Studie eine etwas reduzierte und praxisnähere Stichprobengrösse für die beiden Studiendesigns simuliert. Die Anzahl simulierter Klassen wurde folglich auf 70 und die Klassengrösse auf 12 reduziert. Diese Werte entsprechen nun  den festgelegten Werte aus der Simulation von Moerbeek et al. (2003), die aus dem Datensatz des *Television School and Family Smoking Prevention and Cessation Projekt (TVSFP)* entnommen wurden (Flay et al., 1995). Diese Reduktion führte zu einer Stichprobengrösse von insgesamt 840 Beobachtungen. 

Wie bereits in der Herleitung der Forschungsfrage beschrieben, wurde der Effekt des Treatments mit einem *t* Test überprüft. Die Prüfgrösse berechnet sich aus folgender Formel:
$$
\begin{equation}
t = \dfrac{\widehat{\gamma}}{\widehat{SE}_{\widehat{\gamma}}}
\end{equation}
$$
Dabei ist $\widehat{\gamma}$ der jeweilige geschätzte Regressionskoeffizienten und $\widehat{SE}_{\widehat{\gamma}}$ der dazugehörige Standardfehler. Die Anzahl Freiheitsgrade wurde bei normalen linearen Modellen mittels der bekannten Formel $N + p - 1$ berechnet. Bei den hierarchischen linearen Modellen wurde die Satterthwaite Methode verwendet, um die Anzahl Freiheitsgrade zu bestimmen (Satterthwaite, 1941). Die Satterthwaite Methode ist eine der in der Forschung diskutierten Methoden, die häufig zur Berechnung der Freiheitsgrade von hierarchischen linearen Modellen verwendet wird (Raudenbush & Bryk, 2002; Snijders & Bosker, 2012). 

Um nun die Power zu berechnen, wurde in jeder Bedingung und für jede Analysemethode die Anzahl an Tests, die auf einem Signifikanzniveau von 5% signifikant wurden, durch die Anzahl Replikationen pro Bedingung geteilt. Dies ergibt die prozentuale Häufigkeit, bei der die Analysemethode in der gegebenen IKK Bedingung einen signifikanten Effekt gefunden hat. Da im Simulationsdesign die Intervention in der Tat einen Effekt hat, entspricht diese prozentuale Häufigkeit der Power dieser Analysemethode.