---
title: "text_intro_ml"
author: "noah"
date: "23 3 2020"
output: html_document
---
Hierarchische Daten treten häufig in den Sozialwissenschaften auf, unter anderem auch in der Psychologie. Von hierarchischen Daten wird gesprochen, wenn beispielsweise Daten von Schulkindern innerhalb verschiedener Schulklassen oder von Mitarbeitenden aus mehreren Teams erhoben werden. Aber auch Daten aus Langzeitstudien werden als gruppiert bezeichnet, da mehrere Messzeitpunkte innerhalb einer Person gruppiert sind. 

Hierarchische Daten werden in Levels unterteilt, wobei Daten aus der niedrigsten Stufe als Level-1 Einheiten bezeichnet werden. Ein Beispiel für Level-1 Einheiten sind Schulkinder. Diese Schulkinder befinden sich wiederum in Klassen, die in der Hierarchiestufe höher sind und folglich als Level-2 Einheiten bezeichnet werden. Würde man nun in einer Studie nicht nur Schulkinder in Schulklassen, sondern auch  die Schulen selbst berücksichtigen, würden die Schulen als Level-3 Einheit bezeichnet werden. Die Anzahl der Levels könnte man theoretisch beliebig hoch wählen, solange es das Studiendesign erlaubt und es aus der Perspektive der Forschungsfrage sinnvoll ist.

In der Forschung ist es aus Kostengründen oder aus Gründen des Studiendesigns oft nicht möglich, solche gruppierte Datenstrukturen zu vermeiden. Werden diese hierarchischen Strukturen in der Analyse aber nicht berücksichtigt und mittels einer normalen linearen Regression analysiert, kann dies zu ungenauen Schätzungen führen, die schlussendlich in erhöhten Fehler Typ 1 oder Fehler Typ 2 Raten resultieren. Eine erhöhte Fehler Typ 1 Rate führt dazu, dass die Nullhypothese häufiger verworfen wird und erhöt somit die Chance, dass man irrtümlicherweise ein signifikantes Ergebnis erhält. Eine erhöhte Fehler Typ 2 Rate führt hingegen dazu, dass die Alternativhypothese häufiger verworfen wird. Dies Reduziert folglich die statistische Power einen Effekt zu finden. 

Grundsätzlich lässt sich sagen, dass eine Analyse von hierarchischen Daten mittels unpassenden Methoden zu ungenauen Testergebnissen und folglich zu fehlerhaften Entscheidungen führen kann. Mittels hierarchischen linearen Modellen (HLM) können diese Probleme umgangen werden.